/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Oscar Rivera Serrano
 */
public class VentanaAhorcado extends javax.swing.JFrame {
    
    String palabraOculta = "CETYS";
    
    String [] listaPalabras = {"ORDENADOR", "RATON", "TECLADO", "TECLA"};
    
    int numeroFallos = 0;

    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        dibujaImagen(0);
        palabraOculta = eligePalabraOculta( listaPalabras );
        escribeGuionesEnPantalla();
        System.out.print(palabraOculta);
    }
    //ponemos tantos guiones como letras tenga la palabra
    private void escribeGuionesEnPantalla(){
        String auxiliar = "";
        
        for (int i=0; i<palabraOculta.length(); i++){
            auxiliar = auxiliar + "_ ";
        }
        pantalla.setText(auxiliar);
    } 
    //método random donde elige al azar las palabras
    private String eligePalabraOculta( String [] lista){
        Random aleatorio = new Random ();
        return lista[aleatorio.nextInt( lista.length ) ];
    }
    
    //chequeamos que letra es la que se pulsa y si está en la palabra
    private void chequeaLetra(String letra){
        letra = letra.toUpperCase();
        
        StringBuilder palabraConGuiones = new StringBuilder( pantalla.getText() );
        
        //si la letra esta en la palabra
        if (palabraOculta.contains(letra)){
            for (int i=0; i< palabraOculta.length(); i++ ){
               if (palabraOculta.charAt(i) == letra.charAt(0)){
                   palabraConGuiones.setCharAt(2*i, letra.charAt(0) );
                    
                }
            }
            //no esta la letra, se mantiene el guión
            pantalla.setText(palabraConGuiones.toString() );
        }
        else {
            numeroFallos++;
            dibujaImagen(numeroFallos);
            
        }
    }
    //por cada fallo, ponemos una imagen distinta
    private void dibujaImagen(int numeroImagen){
        URL nombreImagen = null;
        switch (numeroImagen){
            case 0: nombreImagen = getClass().getResource("/imagenes/ahorcado_0.png");break;
            case 1: nombreImagen = getClass().getResource("/imagenes/ahorcado_1.png");break;
            case 2: nombreImagen = getClass().getResource("/imagenes/ahorcado_2.png");break;
            case 3: nombreImagen = getClass().getResource("/imagenes/ahorcado_3.png");break;
            case 4: nombreImagen = getClass().getResource("/imagenes/ahorcado_4.png");break;
            case 5: nombreImagen = getClass().getResource("/imagenes/ahorcado_5.png");break;
            case 6: nombreImagen = getClass().getResource("/imagenes/download_1.jpg");break;
            default : nombreImagen = getClass().getResource("/imagenes/download.jpg");break;
        }
        
        int ancho = panelAhorcado.getWidth();
        int alto = panelAhorcado.getHeight();
        
       ImageIcon miImagen = new ImageIcon( new ImageIcon(nombreImagen).getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
       
        panelAhorcado.setIcon(miImagen);
        
    }
    private void chequeaBoton(JButton miBoton){
        miBoton.setEnabled(false);
        chequeaLetra(miBoton.getText() );
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        panelAhorcado = new javax.swing.JLabel();
        letra = new javax.swing.JButton();
        letra1 = new javax.swing.JButton();
        letra2 = new javax.swing.JButton();
        letra3 = new javax.swing.JButton();
        letra4 = new javax.swing.JButton();
        letra5 = new javax.swing.JButton();
        letra6 = new javax.swing.JButton();
        letra7 = new javax.swing.JButton();
        letra8 = new javax.swing.JButton();
        letra9 = new javax.swing.JButton();
        letra10 = new javax.swing.JButton();
        letra11 = new javax.swing.JButton();
        letra12 = new javax.swing.JButton();
        letra13 = new javax.swing.JButton();
        letra14 = new javax.swing.JButton();
        letra15 = new javax.swing.JButton();
        letra16 = new javax.swing.JButton();
        letra17 = new javax.swing.JButton();
        letra18 = new javax.swing.JButton();
        letra19 = new javax.swing.JButton();
        letra20 = new javax.swing.JButton();
        letra21 = new javax.swing.JButton();
        letra22 = new javax.swing.JButton();
        letra23 = new javax.swing.JButton();
        letra24 = new javax.swing.JButton();
        letra25 = new javax.swing.JButton();
        letra26 = new javax.swing.JButton();
        letra27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Lucida Sans", 0, 48)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pantalla.setText("- - - - - ");

        letra.setText("B");
        letra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letraMousePressed(evt);
            }
        });
        letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letraActionPerformed(evt);
            }
        });

        letra1.setText("C");
        letra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra1MousePressed(evt);
            }
        });
        letra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra1ActionPerformed(evt);
            }
        });

        letra2.setText("D");
        letra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra2MousePressed(evt);
            }
        });
        letra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra2ActionPerformed(evt);
            }
        });

        letra3.setText("E");
        letra3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra3MousePressed(evt);
            }
        });
        letra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra3ActionPerformed(evt);
            }
        });

        letra4.setText("A");
        letra4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra4MousePressed(evt);
            }
        });
        letra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra4ActionPerformed(evt);
            }
        });

        letra5.setText("F");
        letra5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra5MousePressed(evt);
            }
        });
        letra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra5ActionPerformed(evt);
            }
        });

        letra6.setText("G");
        letra6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra6MousePressed(evt);
            }
        });
        letra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra6ActionPerformed(evt);
            }
        });

        letra7.setText("I");
        letra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra7MousePressed(evt);
            }
        });
        letra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra7ActionPerformed(evt);
            }
        });

        letra8.setText("J");
        letra8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra8MousePressed(evt);
            }
        });
        letra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra8ActionPerformed(evt);
            }
        });

        letra9.setText("K");
        letra9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra9MousePressed(evt);
            }
        });
        letra9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra9ActionPerformed(evt);
            }
        });

        letra10.setText("L");
        letra10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra10MousePressed(evt);
            }
        });
        letra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra10ActionPerformed(evt);
            }
        });

        letra11.setText("H");
        letra11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra11MousePressed(evt);
            }
        });
        letra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra11ActionPerformed(evt);
            }
        });

        letra12.setText("M");
        letra12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra12MousePressed(evt);
            }
        });
        letra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra12ActionPerformed(evt);
            }
        });

        letra13.setText("N");
        letra13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra13MousePressed(evt);
            }
        });
        letra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra13ActionPerformed(evt);
            }
        });

        letra14.setText("O");
        letra14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra14MousePressed(evt);
            }
        });
        letra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra14ActionPerformed(evt);
            }
        });

        letra15.setText("P");
        letra15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra15MousePressed(evt);
            }
        });
        letra15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra15ActionPerformed(evt);
            }
        });

        letra16.setText("Q");
        letra16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra16MousePressed(evt);
            }
        });
        letra16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra16ActionPerformed(evt);
            }
        });

        letra17.setText("R");
        letra17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra17MousePressed(evt);
            }
        });
        letra17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra17ActionPerformed(evt);
            }
        });

        letra18.setText("Ñ");
        letra18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra18MousePressed(evt);
            }
        });
        letra18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra18ActionPerformed(evt);
            }
        });

        letra19.setText("S");
        letra19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra19MousePressed(evt);
            }
        });
        letra19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra19ActionPerformed(evt);
            }
        });

        letra20.setText("T");
        letra20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra20MousePressed(evt);
            }
        });
        letra20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra20ActionPerformed(evt);
            }
        });

        letra21.setText("V");
        letra21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra21MousePressed(evt);
            }
        });
        letra21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra21ActionPerformed(evt);
            }
        });

        letra22.setText("W");
        letra22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra22MousePressed(evt);
            }
        });
        letra22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra22ActionPerformed(evt);
            }
        });

        letra23.setText(" ");
        letra23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra23MousePressed(evt);
            }
        });
        letra23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra23ActionPerformed(evt);
            }
        });

        letra24.setText("X");
        letra24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra24MousePressed(evt);
            }
        });
        letra24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra24ActionPerformed(evt);
            }
        });

        letra25.setText("U");
        letra25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra25MousePressed(evt);
            }
        });
        letra25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra25ActionPerformed(evt);
            }
        });

        letra26.setText("Y");
        letra26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra26MousePressed(evt);
            }
        });
        letra26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra26ActionPerformed(evt);
            }
        });

        letra27.setText("Z");
        letra27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                letra27MousePressed(evt);
            }
        });
        letra27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(letra27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letraActionPerformed
         chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letraActionPerformed

    private void letraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letraMousePressed
       chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letraMousePressed

    private void letra1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra1MousePressed
 chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra1MousePressed

    private void letra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra1ActionPerformed
 chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra1ActionPerformed

    private void letra2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra2MousePressed
 chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra2MousePressed

    private void letra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra2ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra2ActionPerformed

    private void letra3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra3MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra3MousePressed

    private void letra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra3ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra3ActionPerformed

    private void letra4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra4MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra4MousePressed

    private void letra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra4ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra4ActionPerformed

    private void letra5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra5MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra5MousePressed

    private void letra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra5ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra5ActionPerformed

    private void letra6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra6MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra6MousePressed

    private void letra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra6ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra6ActionPerformed

    private void letra7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra7MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra7MousePressed

    private void letra7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra7ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra7ActionPerformed

    private void letra8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra8MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra8MousePressed

    private void letra8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra8ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra8ActionPerformed

    private void letra9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra9MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra9MousePressed

    private void letra9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra9ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra9ActionPerformed

    private void letra10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra10MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra10MousePressed

    private void letra10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra10ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra10ActionPerformed

    private void letra11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra11MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra11MousePressed

    private void letra11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra11ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra11ActionPerformed

    private void letra12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra12MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra12MousePressed

    private void letra12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra12ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra12ActionPerformed

    private void letra13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra13MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra13MousePressed

    private void letra13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra13ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra13ActionPerformed

    private void letra14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra14MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra14MousePressed

    private void letra14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra14ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra14ActionPerformed

    private void letra15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra15MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra15MousePressed

    private void letra15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra15ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra15ActionPerformed

    private void letra16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra16MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra16MousePressed

    private void letra16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra16ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra16ActionPerformed

    private void letra17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra17MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra17MousePressed

    private void letra17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra17ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra17ActionPerformed

    private void letra18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra18MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra18MousePressed

    private void letra18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra18ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra18ActionPerformed

    private void letra19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra19MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra19MousePressed

    private void letra19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra19ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra19ActionPerformed

    private void letra20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra20MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra20MousePressed

    private void letra20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra20ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra20ActionPerformed

    private void letra21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra21MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra21MousePressed

    private void letra21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra21ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra21ActionPerformed

    private void letra22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra22MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra22MousePressed

    private void letra22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra22ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra22ActionPerformed

    private void letra23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra23MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra23MousePressed

    private void letra23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra23ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra23ActionPerformed

    private void letra24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra24MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra24MousePressed

    private void letra24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra24ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra24ActionPerformed

    private void letra25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra25MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra25MousePressed

    private void letra25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra25ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra25ActionPerformed

    private void letra26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra26MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra26MousePressed

    private void letra26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra26ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra26ActionPerformed

    private void letra27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_letra27MousePressed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra27MousePressed

    private void letra27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra27ActionPerformed
        chequeaBoton( (JButton) evt.getSource());
    }//GEN-LAST:event_letra27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton letra;
    private javax.swing.JButton letra1;
    private javax.swing.JButton letra10;
    private javax.swing.JButton letra11;
    private javax.swing.JButton letra12;
    private javax.swing.JButton letra13;
    private javax.swing.JButton letra14;
    private javax.swing.JButton letra15;
    private javax.swing.JButton letra16;
    private javax.swing.JButton letra17;
    private javax.swing.JButton letra18;
    private javax.swing.JButton letra19;
    private javax.swing.JButton letra2;
    private javax.swing.JButton letra20;
    private javax.swing.JButton letra21;
    private javax.swing.JButton letra22;
    private javax.swing.JButton letra23;
    private javax.swing.JButton letra24;
    private javax.swing.JButton letra25;
    private javax.swing.JButton letra26;
    private javax.swing.JButton letra27;
    private javax.swing.JButton letra3;
    private javax.swing.JButton letra4;
    private javax.swing.JButton letra5;
    private javax.swing.JButton letra6;
    private javax.swing.JButton letra7;
    private javax.swing.JButton letra8;
    private javax.swing.JButton letra9;
    private javax.swing.JLabel panelAhorcado;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
